colorful debug:error info,let uploadXXX echoes absolute pathname.

diff --git a/scripts/functions/base b/scripts/functions/base
--- a/scripts/functions/base
+++ b/scripts/functions/base
@@ -41,11 +41,16 @@ function echotest(){
 # iisr=if i say right
 function iisr(){
 	#"$1" is a expression ,value is boolean '1' or '0'
-	if test $1;then
+#	if test $1;then
+	eval "test $1"
+	if test $? -eq 0;then
 		echo "::TRUE:: ""$1" 
 	else
-		echo "::ERROR:: ""$1" 
+	# add colorfully text
+		echo -e  "\033[1;31m::ERROR:: $1\033[0m" 
 	fi
 }
+
+
 #invoke include method now.
 include_all
